name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 2:30 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file (23f2000547@ds.study.iitm.ac.in)
        run: |
          date >> daily-log.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "23f2000547@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily update: $(date)"
          git push
